//! Storage where are stored all token for OTP authentication

/// Error generated by storage
pub enum Error {}

/// Storage definition
pub trait Storage {
    /// Get token by it's identifier
    fn get_token(&self, id: &str) -> Result<crate::Token, Error>;
    /// Return a list of all stored tokens
    fn list_tokens(&self) -> Result<Vec<crate::Token>, Error>;
    /// Add/Set token into storage (overwrite existing token)
    fn set_token(&mut self, token: crate::Token) -> Result<(), Error>;
}
